version: "3.8"
services:
  ws-to-mongo:
    image: reosiain/billy:ws_to_mongo
    container_name: ws_to_mongo
    environment:
      - TZ=Europe/Moscow
      - WS_ADDRESS=${WS_ADDRESS}
      - MONGO_URI=mongodb://${DB_URI_WO_PORT}:1000
      - SUBSCRIPTION_PARAMS=${SUBSCRIPTION_PARAMS}
      - DB_NAME=${DB_NAME}
      - OHLC_COLLECTION_NAME=${OHLC_COLLECTION_NAME}
      - WS_LOGGER_PATH=${WS_LOGGER_PATH}
    volumes:
      - ./internals:/internals
    restart: unless-stopped
    networks:
      net_internal:
        ipv4_address: ${WS_TO_MONGO_HOST}
    depends_on:
      mongodb:
        condition: service_healthy

  python-dependencies:
    image: reosiain/billy:python_base
    container_name: python-dependencies
    command: sleep infinity
    volumes:
      - dependencies-path:/venv
    depends_on:
      mongodb:
        condition: service_healthy

  trading-service:
    image: reosiain/billy:crypto_trading_service
    container_name: trading-service
    environment:
      - TZ=Europe/Moscow
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - API_PASS=${API_PASS}
      - DB_URI=${DB_URI_WO_PORT}
      - DB_PORT=1000
      - DB_NAME=${DB_NAME}
      - OHLC_COLLECTION_NAME=${OHLC_COLLECTION_NAME}
      - TRADE_COLLECTION_NAME=${TRADE_COLLECTION_NAME}
      - PAIRS=${PAIRS}
      - MODEL_PATH=${MODEL_PATH}
      - LOGGER_PATH=${LOGGER_PATH}
    volumes:
      - dependencies-path:/venv
      - ./model:/model
      - ./internals:/internals
    ports:
      - "1001:1001"
    networks:
      - net_internal
    depends_on:
      - python-dependencies

  mongodb:
    image: mongo
    container_name: mongodb
    command: mongod --quiet --port 1000 --logpath /data/log/mongolog --bind_ip ${DB_URI_WO_PORT}
    environment:
      - TZ=Europe/Moscow
      - PUID=1000
      - PGID=1000
    volumes:
      - ./internals/db/data:/data/db
      - ./internals/db/mongolog:/data/log
    ports:
      - "1000:1000"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.stats().ok' || exit 1
      interval: 10s
      timeout: 5s
      retries: 0
      start_period: 12s
    networks:
      net_internal:
        ipv4_address: ${DB_URI_WO_PORT}

networks:
  net_internal:
    ipam:
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

volumes:
  dependencies-path:

