version: "3.8"
services:
  ws-to-mongo:
    image: reosiain/crypto:ws_to_mongo
    command:
      "./build/bin/ws_to_mongo"
    container_name: ws_to_mongo
    environment:
      - WS_ADDRESS=${WS_ADDRESS}
      - MONGO_URI=${MONGO_URI}
      - SUBSCRIPTION_PARAMS=${SUBSCRIPTION_PARAMS}
    ports:
      - "1000:1000"
    restart: unless-stopped
    networks:
      net_internal:
        ipv4_address: ${WS_TO_MONGO_HOST}

  trading_service:
    image: reosiain/crypto:trading_service
    command: "src/launcher.py"
    container_name: trading_service
    environment:
      - OKEX_REST_API=${OKEX_REST_API}
      - MONGO_URI=${MONGO_URI}
      - SUBSCRIPTION_PARAMS=${SUBSCRIPTION_PARAMS}
    ports:
      - "1001:1001"
    restart: unless-stopped
    networks:
      net_internal:
        ipv4_address: ${TRADING_SERVICE_HOST}
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    command: mongod --quiet --port 1002 --bind_ip ${MONGO_HOST}
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo/database:/data/db
      - ./source:/data/log
    ports:
      - "1002:1002"
    restart: unless-stopped
    networks:
      net_internal:
        ipv4_address: ${MONGO_HOST}

networks:
  net_internal:
    external: false
    ipam:
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

  net_external:
    external: true
    name: net_external



