FROM continuumio/miniconda3 AS build

COPY environment.yml .
RUN conda env create --file environment.yml
RUN conda install -c conda-forge conda-pack

# Use conda-pack to create a standalone enviornmen in /venv:
RUN conda-pack -n build -o /tmp/env.tar && \
  mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
  rm /tmp/env.tar

RUN /venv/bin/conda-unpack


FROM alpine:latest AS runtime
COPY --from=build /venv /venv
SHELL ["/bin/bash", "-c"]
